version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    links:
       - db

volumes:
  mysql_data:
  gem_data: